### PR TITLE
Main grammar revision: Completed. Next, possible minor revision and improvements.

### PR DESCRIPTION
**Pull request by icaroperseo**
Please consider this pull request.

Thanks in advance!

### CODE REVIEW

**Comment by icaroperseo** [comment]
This is all for the moment.

**Comment by gapan** [comment]
I have made a few commends in some places. Can you look into them? Overall you have done a great job! I will merge as soon as we clear those few issues.

**Comment by icaroperseo** [comment]
First of all, a big apology for the delay. I had not understood correctly that you needed me to do the corrections the notes you included (language problems, my fault!). I think they were made all the corrections.

Glad to return to the work! ^.^

**Comment by gapan** [comment]
Thank you very much! Sorry for taking so long to respond too. :)

**Pull request merged**
